# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


#### 1. Import the numpy package under the name `np` (★☆☆)

In [2]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [2]:
print(np.__version__)
print(np.show_config())

1.18.5
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
None


#### 3. Create a null vector of size 10 (★☆☆)

In [3]:
null = np.zeros(10)
print(null)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)

In [4]:
a = np.array([34,788,98, 975, 500, 67])
print(a)
# findnumber of bytes
print(a.nbytes)
# find size, number of elements, and multiply by the size of an item
print(a.size * a.itemsize)

[ 34 788  98 975 500  67]
48
48


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [5]:
# by typing the following (had to look this up..):
# python -c "import numpy; numpy.info(numpy.add)"

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [6]:
n = np.zeros(10)
n[4] = 5
print(n)

[0. 0. 0. 0. 5. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [7]:
a = np.arange(10,50)
print(a)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]



#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [8]:
# reverse option 1, reverse a from above
a = a[::-1]
print(a)
# reverse option 2, reverse a again so gives back a from above
flip = np.flip(a)
print(flip)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [9]:
th = np.arange(9).reshape(3,3)
print(th)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [10]:
a = np.array([1,2,0,0,4,0])
print(a)
nz = np.where(a!=0)
print(f'Indices non-zero elements: {nz}')

[1 2 0 0 4 0]
Indices non-zero elements: (array([0, 1, 4]),)


#### 11. Create a 3x3 identity matrix (★☆☆)

In [11]:
i = np.eye(3,3)
print(i)
# you don't need to specify the full shape 'cause an Identity matrix has same dimensions
i = np.eye(3)
print(i)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [12]:
r = np.random.randint(100, size=(3,3,3))
print(r)

[[[96 55  5]
  [50 82 86]
  [16 57 89]]

 [[56  4  5]
  [63 53 27]
  [53 13  0]]

 [[47 52 32]
  [70 71 19]
  [24 94 89]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [13]:
r = np.random.randint(70,size=(10,10))
print(r)
print(r.max())
print(r.min())

[[37 61 40 32 66 58 15 36  7 35]
 [10 53 14 22  2  7 25 20 10 41]
 [11 65 57 23 10 27 37 20 56 63]
 [50 45 39 44 11 61  9 45 41 13]
 [48 12 58 32  2 32 24 69 15 24]
 [13 16 29 52 18 60 62 19  5 13]
 [11  3 69  4  1 27 30 57 68 27]
 [ 7 31  5  7  3 20 28 19 42 28]
 [ 0 56 10 67 23 31  1  0 38 38]
 [13 37 45 28 18 54 32 33 26 12]]
69
0


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [14]:
r = np.random.randint(65, size=30)
print(r)

print(r.mean())
# or
m = np.mean(r)
print(m)

[ 9  6 46 21 40 53 25 63 27 31  8 39 63 10 39 35 31 58 10 10 23 39 10 36
 56  7 50  3 53 58]
31.966666666666665
31.966666666666665


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [18]:
two = np.ones((5,6)) # repeat with non square matrix, use shape[]
n = two.shape[0]
k = two.shape[1]

two[1:n-1,1:n-k ] = 0

print(two)

[[1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [19]:
# if you don't want to go vstacking and hstacking then use np.pad!
zer = np.pad(two, 1)
print(zer)

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [33]:
0 * np.nan

nan

In [34]:
np.nan == np.nan 

False

In [35]:
np.inf > np.nan

False

In [36]:
np.nan - np.nan

nan

In [37]:
np.nan in set([np.nan])

True

In [38]:
0.3 == 3 * 0.1 # https://docs.python.org/3/tutorial/floatingpoint.html, 0.3 and 0,1 are binary fractions

False

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [30]:
# np.diagonal extracts values on diagonal or on offset, here -1 on the diagonal below the 
a = np.random.randint(20,size=(5,5))
print(a)
dia = a.diagonal(-1)
print(dia)

# to create an array with specific values on the diagonal we ca use np.diagflat
di = np.diagflat([1,2,3,4,5], -1) # offset -1
print(f'\nCreate an array with certain values just below the diagonal: \n {di}')

[[18 11 15 17 14]
 [13  5  9 18 10]
 [ 5  6 13  9  3]
 [18 12  0  0  4]
 [ 4  3  3 10  0]]
[13  6  0 10]

Create an array with certain values just below the diagonal: 
 [[0 0 0 0 0 0]
 [1 0 0 0 0 0]
 [0 2 0 0 0 0]
 [0 0 3 0 0 0]
 [0 0 0 4 0 0]
 [0 0 0 0 5 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [45]:
ch = np.zeros((8,8))
ch[0:8:2,0:8:2] = 1
ch[1:8:2,1:8:2] = 1
print(ch)
# Try it by setting items with both even index values to 1? => in progress !!
# ev = np.where(ch[i%2==0,j%2==0], 1)
#print(ev)

[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [21]:
# This gives value of the 100th element but not (x,y,z) index
a = np.random.randint(200,size=(6,7,8))
print(a)
print(f'\nFlatten array and take el at index [99] gives 100th el: {a.flatten()[99]}')
print(f'Same with np.take(a,99) : {np.take(a,99)}')
print(f'Same with a.item(99): {a.item(99)}')

# Finding index of 100th element with some simple calculations!!
print(f'\nNow for the INDEX....')
#n = a.shape[0] 
#k = a.shape[1]
#l = a.shape[2]
n,k,l = a.shape # more concise then above

# print(100//(k*l)) # integer division of el number by rows*columns, returns index dimension 1
# print(100%(k*l)) # remainder integer division above
# print((100%(k*l))//l) # divide remainder by number of columns, returns index dimension 2
# print(((100%(k*l))%l)-1) # remainder above - 1 returns index dimension 3 

ind = (100//(k*l), ((100%(k*l))//l),((100%(k*l))%l)-1)
print(f'\nIndex of 100th el: {ind}')

num = a[(100//(k*l), ((100%(k*l))//l),((100%(k*l))%l)-1)]
print(f'\nCheck number with this index: {num}')

[[[113  57 162 162 170  70 131 106]
  [ 45 186  14  65 181 169 109 182]
  [ 55  78  40 184 161  41 165 192]
  [ 14  90  92 125  43 108  85  91]
  [ 45 168  98   9 140 105  49  17]
  [ 70 176 112  30   8 146  67 146]
  [164 148   8 124 155 155   5   0]]

 [[ 87 197 140  32 103 189 190 122]
  [ 25  54  16 150 156  76  55 161]
  [120  23  10  89  18  27 163  92]
  [ 83 180   9  54  41  88 186 142]
  [126  61 185 113 131  74  69 181]
  [131 178  48 148 113 127  70  92]
  [103  28 154   4  67 192  99  21]]

 [[ 54 149  97   3 105  85  37 144]
  [ 83   2  28 105 111 193 194 163]
  [120 159  70 124 141   8  12 185]
  [ 11 142   4  62   0 159 149 179]
  [ 13 168  59 187 115 108 145  38]
  [176  36  57   8  72 121 154 165]
  [119  47 180  29 184  69  86 162]]

 [[ 94  14  71 186 157  99 136 109]
  [ 25  57 155 126  74 128  97 175]
  [ 94 109 178  59 167 116 164  36]
  [ 62  73 169 177 157  93 160  50]
  [ 23 181 199  39  57  42  89  67]
  [164  87  38 189 104  17  85  60]
  [ 89 189 164 115 143

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [66]:
a = np.array([[0,1],[1,0]])
ch = np.tile(a, (4,4))
print(ch)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [51]:
# np.random.randn : return a sample (or samples) from the “standard normal” distribution.
nor = np.random.randn(5,5) 
print(nor)

# To actually normalize an existing array use np.linalg.norm() =  normalize vector to norm 1 !!!!
a = np.random.randint(100,size=(5,5))
b = np.linalg.norm(a)
print(f'\n np.linalg.norm(a) or norm of a: {b}')
print(f'\nNormalize matrix to norm 1:\n{a/b}')

# To normalize or rescale values between [0,1]:
n = (a- np.min(a))/(np.max(a) -np.min(a))
print(f'\nrescaled between 0 and 1:\n {n}')

# Actual Normalizing:
no= a

[[-1.19259127  1.13095317 -1.29003983  0.16403918 -0.68637515]
 [-0.22145004 -0.85442301  0.63772876  0.76966133  0.73491034]
 [-2.37044733  1.63284551 -0.03987517  0.71278652 -0.0768529 ]
 [-0.66855831 -0.96337188  0.80584221  0.55206491 -0.36468574]
 [ 0.66079165  0.98373121 -1.12713958 -0.18900816 -0.52272668]]

 np.linalg.norm(a) or norm of a: 309.15853538273853

Normalize matrix to norm 1:
[[0.23289022 0.21671729 0.25876691 0.0711609  0.0485188 ]
 [0.22965564 0.22318646 0.19407519 0.00646917 0.2393594 ]
 [0.21995188 0.08733383 0.32022406 0.24906315 0.30405112]
 [0.31375488 0.1423218  0.09380301 0.08733383 0.04204962]
 [0.30405112 0.07439549 0.00970376 0.23612481 0.15202556]]

rescaled between 0 and 1:
 [[0.72164948 0.67010309 0.80412371 0.20618557 0.13402062]
 [0.71134021 0.69072165 0.59793814 0.         0.74226804]
 [0.68041237 0.25773196 1.         0.77319588 0.94845361]
 [0.97938144 0.43298969 0.27835052 0.25773196 0.11340206]
 [0.94845361 0.21649485 0.01030928 0.73195876 0.463

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [46]:
dt = np.dtype({'names': ['r','g','b','a'],
        'formats': [np.uint8, np.uint8, np.uint8, np.uint8]}) # 8 bit = 1 byte (2**3)

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [93]:
a = np.random.randint(100,size=(5,3))
b = np.random.randint(100, size=(3,2))
# first way
m = a @ b
print(m)
# second way
m2 = a.dot(b)
print(m2)
print(m==m2)

[[ 7392  8158]
 [ 6731   591]
 [10577  8281]
 [ 2841  3993]
 [ 2757  6837]]
[[ 7392  8158]
 [ 6731   591]
 [10577  8281]
 [ 2841  3993]
 [ 2757  6837]]
[[ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [50]:
a = np.arange(20)
print(a)

a = np.where((a>3) & (a<8),-a,a) # change in place with np.where()
print(a)

#b = np.where((a>3) & (a<8),-a,a) # just returns a now 'cause a>3) & (a<8) is not true anymore
#print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 0  1  2  3 -4 -5 -6 -7  8  9 10 11 12 13 14 15 16 17 18 19]


In [57]:
# or
a = np.arange(20)
a[(a>3) & (a<8)] *= -1
print(a)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10 11 12 13 14 15 16 17 18 19]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [39]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

10
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [50]:
Z = np.random.randint(100, size=(3,3))
print(Z)

[[95 45 44]
 [ 1  3 48]
 [51  5 71]]


In [51]:
Z**Z # Z raised to the order Z

array([[-3660930864499998817,  2604998672350111773,                    0],
       [                   1,                   27,                    0],
       [ 2823291043684304491,                 3125, -5821812116355782473]])

In [52]:
2 << Z >> 2
# The operators << and >> are bit shift operators (left and right, respectively). 
# In your particular example (with <<), you are performing x = x * 2^z for each array element,
# resulting in your modified output. 
# The operator >> in the same example would yield an output characterized by x = x / 2^z for each array element. 

array([[               0,   17592186044416,    8796093022208],
       [               1,                4,  140737488355328],
       [1125899906842624,               16,                0]])

In [53]:
Z <- Z    # smaller then its negative version, Z < (-Z)

array([[False, False, False],
       [False, False, False],
       [False, False, False]])

In [54]:
1j*Z # as part of complex number

array([[0.+95.j, 0.+45.j, 0.+44.j],
       [0. +1.j, 0. +3.j, 0.+48.j],
       [0.+51.j, 0. +5.j, 0.+71.j]])

In [55]:
Z/1/1 # twice division by 1

array([[95., 45., 44.],
       [ 1.,  3., 48.],
       [51.,  5., 71.]])

In [56]:
Z<Z>Z # not legal, can't be larger or smaller than itself

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

#### 28. What are the result of the following expressions?
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [40]:
np.array(0) / np.array(0)

nan

In [41]:
np.array(0) // np.array(0)

0

In [42]:
np.array([np.nan]).astype(int).astéype(float) # nan as int gives the max representable number in the int range

array([-9.22337204e+18])

#### 29. How to round away from zero a float array ? (★☆☆)

In [68]:
# Generate random float array:
# To sample Unif[a, b), b > a multiply the output of random_sample by (b-a) and add a: 
# b - a) * random_sample() + a
# So for range between [-5,4)
f = 9 * np.random.random_sample((3, 2)) -5
print(f)

# Now round away from zero: np.ceil if x> 0, np.floor if x<0, 'cause np.ceil changes -1.5 to -1 !!!!!!
# np.floor for a negative rounds to a smaller number which is of course rounding away from 0 !
f = np.where(f<0,np.floor(f),np.ceil(f))
print(f)

[[-3.86485006 -0.17251845]
 [-0.75462583 -0.1076588 ]
 [-0.19570641 -1.67072525]]
[[-4. -1.]
 [-1. -1.]
 [-1. -2.]]


In [72]:
# Generating ramdom array of floats with np.random.uniform()
a = np.random.uniform(-10,+10,(5,5))
print(a)
a = np.where(a<0,np.floor(a),np.ceil(a))
print(a)

[[-6.0397359  -3.81403228 -1.89189087 -5.87408017  4.27050488]
 [-5.05243946  6.90840534  0.77934087  2.17518514 -1.87487626]
 [-0.36598883  0.73665319  1.60991685 -5.49434919 -5.69191252]
 [ 6.91138245  6.33137406 -5.65673833  0.72756833 -0.83642407]
 [ 4.99063639 -1.57912667  9.39141854  3.90243254 -9.92372511]]
[[ -7.  -4.  -2.  -6.   5.]
 [ -6.   7.   1.   3.  -2.]
 [ -1.   1.   2.  -6.  -6.]
 [  7.   7.  -6.   1.  -1.]
 [  5.  -2.  10.   4. -10.]]


#### 30. How to find common values between two arrays? (★☆☆)

In [77]:
a = np.random.randint(10, size=(3,3))
b = np.random.randint(10, size=(3,3))
print(a,"\n",b)
print(a==b) # boolean array
print(f'Indices whera a==b: {np.where(a==b)}') # indices common values
print(f'Common values : {a[a==b]}') # common values


[[5 7 3]
 [5 0 3]
 [6 9 7]] 
 [[5 6 3]
 [5 0 3]
 [8 7 0]]
[[ True False  True]
 [ True  True  True]
 [False False False]]
Indices whera a==b: (array([0, 0, 1, 1, 1]), array([0, 2, 0, 1, 2]))
Common values : [5 3 5 0 3]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [72]:
# import warnings
# warnings.filterwarnings('ignore')
# test
np.array(0) // np.array(0) # not more warning showing up

# Below solution I had to look up
# Suicide mode on
#defaults = np.seterr(all="ignore")
#Z = np.ones(1) / 0

# Back to sanity
#_ = np.seterr(**defaults)

0

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [57]:
np.sqrt(-1) == np.emath.sqrt(-1)

False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [78]:
print(f"Yesterday : {np.datetime64('today') - np.timedelta64(1,'D')}")
print(f"Today : {np.datetime64('today')}")
print(f"Tomorrow : {np.datetime64('today') + np.timedelta64(1,'D')}")

Yesterday : 2020-11-08
Today : 2020-11-09
Tomorrow : 2020-11-10


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [89]:
# Use np.arange to get ranges of dates!

month = np.arange('2016-07','2016-08', dtype= 'datetime64[D]')
print(month)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [96]:
a = np.random.randint(50,size=(5,3))
b = np.random.randint(35,size=(3,4))
print(f'{a}\n{b}')
b = np.add(a,b)
print(f'{a}\n{b}')

[[30  2 29]
 [33 17 18]
 [47 14 34]
 [ 2 39  8]
 [32 49 27]]
[[27 25 15 25]
 [ 3  1 22 18]
 [ 5 29 11 13]]


ValueError: operands could not be broadcast together with shapes (5,3) (3,4) 

#### 36. Extract the integer part of a random array using 5 different methods (★★☆)

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

#### 40. Create a random vector of size 10 and sort it (★★☆)

#### 41. How to sum a small array faster than np.sum? (★★☆)

#### 42. Consider two random array A and B, check if they are equal (★★☆)

#### 43. Make an array immutable (read-only) (★★☆)

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

#### 49. How to print all the values of an array? (★★☆)

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [ ]:
# isclose

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [ ]:
# astype(int32)

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [ ]:
# is that randn?

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

In [ ]:
# use np.mean(axis=0)

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

In [ ]:
# isclose

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)